name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Build
        run: npm run build

      - name: Deploy to GitHub Pages
        env:
          USER_NAME: ${{ secrets.USER_NAME }}
          USER_EMAIL: ${{ secrets.USER_EMAIL }}
        run: |
          git config --global user.name "${USER_NAME}"
          git config --global user.email "${USER_EMAIL}"
          git checkout gh-pages  
          rm -rf *  
          cp -r ../dist/* .  
          git add .
          git commit -m 
          git push origin gh-pages
